# Generated by Django 3.2.5 on 2021-08-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing_listingcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
