# Generated by Django 3.2.5 on 2021-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
