# Generated by Django 3.2.5 on 2021-08-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
